eureka:
    client:
        fetchRegistry: false
        registerWithEureka: false
    instance:
        hostname: localhost
    server:
        enable-self-preservation: false
server:
    port: 8761
