server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/FileShare
    username: postgres
    password: password

security:
  password:
    encoding:
      strength: 10
      
management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  client:
    config:
      default:
        connectTimeout: 80000
        readTimeout: 80000