server:
  port: 8083
  error:
    include-message: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/FileShare
    username: postgres
    password: password

security:
  password:
    encoding:
      strength: 10
  jwt:
    secret-key: secret
    validity-time: 1200000
    signature-algorithm: HS256
