server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/authUser
      globalcors:
        cors-configurations: 
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
        
management:
  endpoints:
    web:
      exposure:
        include: '*'

