server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:

        - id: user-service-public
          uri: lb://user-service
          predicates:
            - Path=/user
            - Method=POST
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - Authorization=ROLE_USER
        
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/authUser

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file/**
          filters:
            - Authorization=ROLE_USER

      globalcors:
        cors-configurations: 
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
        add-to-simple-url-handler-mapping: true
        
management:
  endpoints:
    web:
      exposure:
        include: '*'


security:
  password:
    encoding:
      strength: 10
  jwt:
    secret-key: secret
    validity-time: 1200000
    signature-algorithm: HS256
